# Generated by Django 5.0.3 on 2024-04-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('profimg', models.ImageField(default='blank-profile-picture.png', upload_to='prof_imgs')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
