# Generated by Django 5.0.3 on 2024-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='location',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
