# Generated by Django 5.0.3 on 2024-04-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0008_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='followersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
